set nocompatible              " be iMproved, required for vundle
filetype off                  " required for vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ctrlpvim/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax on  " turn on syntax highlighting

set backspace=indent,eol,start  " Sane backspace behavior

" turn on line numbers in a 6 column gutter
set number
set relativenumber
set numberwidth=6
highlight LineNr ctermbg=233 ctermfg=253
highlight CursorLineNr ctermbg=green ctermfg=black

" Disable the arrow keys
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>
vnoremap <Left> :<C-u>echoe "Use h"<CR>
vnoremap <Right> :<C-u>echoe "Use l"<CR>
vnoremap <Up> :<C-u>echoe "Use k"<CR>
vnoremap <Down> :<C-u>echoe "Use j"<CR>
inoremap <Left> <C-o>:echoe "Use h"<CR>
inoremap <Right> <C-o>:echoe "Use l"<CR>
inoremap <Up> <C-o>:echoe "Use k"<CR>
inoremap <Down> <C-o>:echoe "Use j"<CR>

" Markdown settings
" ------------
augroup filetype_markdown
  autocmd!
  autocmd BufNewFile,BufRead *.md set filetype=markdown
  " softwrap at 80 characters
  autocmd FileType markdown setlocal wrap linebreak nolist textwidth=0 wrapmargin=0 columns=80
  " reset the softwrap width after vim (e.g. the window) is resized
  autocmd Filetype markdown autocmd VimResized * if (&columns > 80) | setlocal columns=80 | endif
  " turn on spell check
  autocmd FileType markdown setlocal spell
augroup END

" Silver searcher for CtrlP from
" from https://robots.thoughtbot.com/faster-grepping-in-vim
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " use in CtrlP for listing files fast and respecting .gitignore
  let g:ctrlp_user_command = 'ag -Q -l --nocolor --hidden -g "" %s'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  if !exists(":Ag")
    command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
    nnoremap \ :Ag<SPACE>
  endif
endif
