
force_color_prompt=yes

source ~/.dotfiles/osx/config.global.sh
if [ -f ~/.dotfiles/osx/config.local.sh ]; then
  source ~/.dotfiles/osx/config.local.sh
fi

source ~/.dotfiles/git/bin/git-completion.sh
source ~/.dotfiles/git/bin/git-prompt.sh

if [ -f /Volumes/*/pier-11/codebase/lightster/pier-cli/bin/bash_functions.sh ]; then
  source /Volumes/*/pier-11/codebase/lightster/pier-cli/bin/bash_functions.sh
fi

# http://unix.stackexchange.com/a/31697/85908
RESET="\[$(tput sgr0)\]"
BOLD="\[$(tput bold)\]"
BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
MAGENTA="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
WHITE="\[$(tput setaf 7)\]"

HOST='\h'
CWD='\w'
GIT='$(__git_ps1 " (%s)")'
TIME='\t'
PS1="\n[$GREEN$TIME $RED$HOST$WHITE:$BLUE$CWD$YELLOW$GIT$WHITE]"
PS1="$PS1\n    $PURPLE\$$RESET "

alias cd='echo "💜 💙 💚 " ; cd'
alias meow='echo "🐱 "'
alias ssh='echo "🚒  🚒   🚒     🚒          🚒            🚒   " ; ssh'

export HISTFILESIZE=
export HISTSIZE=

ls --color=auto >/dev/null 2>&1
if [ $? -eq 0 ]; then
    alias ls='ls -GF --color=auto'
else
    alias ls='ls -GF'
fi
alias ll='ls -l'
alias sudo='sudo '

alias ~='cd ~'
alias c='cd'
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias g='git'
alias v='vagrant'
alias a='atom-beta'
alias atom='a'

alias ie-dev="cd ${SERVER_PATH}/illuminate.local/vm"
alias lds="cd ${SERVER_PATH}/lightdatasys.local"
alias ldsv="cd ${SERVER_PATH}/lightdatasys.local/linode-vagrant"
alias autobox="cd ${SERVER_PATH}/lightdatasys.local/autobox"

alias ie='ie-dev'
alias pd="cd ${SERVER_PATH}/lightdatasys.local/linode-vagrant/codebase"
alias qs="cd ${SERVER_PATH}/lightdatasys.local/linode-vagrant/codebase/quick-switcher"
alias ravens="cd ${SERVER_PATH}/lightdatasys.local/linode-vagrant/codebase/ravens"
alias hodor="cd ${SERVER_PATH}/lightdatasys.local/linode-vagrant/codebase/hodor-dev"
alias dotfiles="cd ~/.dotfiles"
alias pb='cd ~/Dropbox/playbook'
alias atd='cd ${SERVER_PATH}/illuminate.local/vm/illuminate/codebase/allthedata/master'
alias pi='cd ${SERVER_PATH}/*.local/pier-11'

# added by travis gem
[ -f /Users/lightster/.travis/travis.sh ] && source /Users/lightster/.travis/travis.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
